import './App.css';
import KeyboardArrowDownIcon from '@mui/icons-material/KeyboardArrowDown';

function App() {

  const BASE_URL = window.location.origin + "/munch-landing";

  return (
    <div className="App container-fluid mt-5">
      <div className="container d-flex flex-column align-items-center">
            <div>
              <h1 style={{textAlign: "center"}}>Welcome to</h1>
              <img className='m-0 p-0' src={BASE_URL + '/assets/munchLogo.png'} alt='Munch Logo'></img>
            </div>
        </div>

        <div className="container flex-column align-items-center ">
            <div style={{textAlign: "center", marginTop: "75px"}}>
                <h3>We empower restaurants to build</h3>
                <h3>lasting customers by establishing</h3>
                <h3>community online</h3>
            </div>
        </div>

        <div className="container flex-column align-items-center ">
            <div style={{textAlign: "center", marginTop: "350px"}}>
                <h3>Scroll to find out more</h3>
                <KeyboardArrowDownIcon htmlColor="#000000" />
            </div>
        </div>

        <div className="container flex-column align-items-center ">
            <div style={{marginTop: "100px"}}>
                <h3 style={{fontWeight: "600"}}>How it works</h3>
                <p>Munch Leverages Meta's Instragram Graph API, a tool that allows sites
                    to post directly to Instagram, so that <strong>restaurants in Seattle's University District </strong>
                can share content to a <strong>community Instagram page.</strong>
                </p>
                <img src={BASE_URL + "/assets/munchInstagramLogo.png"} alt="Landing 1"></img>
            </div>
        </div>

        <div className="container flex-column align-items-center ">
            <div style={{marginTop: "100px", textAlign: "right"}}>
                <h3 style={{fontWeight: "600"}}>Why Munch?</h3>
                <p>
                    We met with restaurant owners and found that a common struggle is <strong>customer retention. </strong> 
                    Social media is an <strong>essential marketing tool,</strong> but it is often difficult to create 
                    and maintain an online business presence. Munch is an easy-to-use platform that 
                    <strong> reduces the stress</strong> of running a social media account. By integrating posts from many restaurants, 
                    our Instagram page has an endless stream of interesting content that will be accessible for generations of 
                    potential customers.
                </p>
            </div>
        </div>

        <div className="container flex-column align-items-center ">
            <div style={{textAlign: "center", marginTop: "75px"}}>
                <p>
                    Visit @munchrestaurants on Instagram to see what the community is saying
                </p>
            </div>
        </div>

        <div className="container flex-column align-items-center ">
            <div style={{marginTop: "100px", textAlign: "right"}}>
                <h3 style={{fontWeight: "600"}}>Disclaimer & Acknowledgement</h3>
                <p>
                    Please note that as part of our solution we have implemented a <strong>chat feature</strong> to help users with creative 
                    Instagram captioning and any social media questions they may have. This chat feature on our app utilizes 
                    an <strong>AI-powered</strong> language model to provide responses. While we strive to ensure the accuracy and relevance 
                    of the information provided by the chatbot, please be advised that the responses generated by the AI model 
                    are based on its training and programming, and may not always be error-free or reflect the opinions or 
                    views of our company. We strongly encourage you to exercise your own judgement and discretion when 
                    relying on the information provided by the chatbot.
                </p>
                <p>
                We would like to acknowledge the use of an AI-powered chatbot in our app, which is powered by <strong>OpenAI's
                GPT-3.5</strong> language model and Social Intents. We recognize the valuable contribution of this technology in enhancing the user 
                experience and providing a more interactive and personalized service to our users. However, we also 
                acknowledge the limitations and potential risks associated with the use of AI, and we remain committed 
                to ensuring the responsible and ethical use of this technology in our app.

                </p>
            </div>
        </div>

        <div className="container flex-column align-items-center ">
            <div style={{textAlign: "center", marginTop: "250px"}}>
                <h3 style={{fontWeight: "600"}}>Meet the Creators</h3>
                <p>
                    Munch was founded by a team of undergraduate students at the University of Washington’s iSchool. 
                    Over the course of 20 weeks, we researched, designed, and developed our the Munch 
                    web app alongside restaurant owners and managers in the University District. Our app will be going <strong>open-source</strong> at the end of the Spring 2023 quarter on 6/1/2023.
                </p>
            </div>
        </div>

        <div className="container flex-row w-auto">
            <div className="row">
                <div className="col">
                    <img src={BASE_URL + "/assets/team2.png"} alt="team 2"></img>
                </div>
                <div className="col">
                    <img src={BASE_URL + "/assets/team1.png"} alt="team 1"></img>
                </div>
                <div className="col">
                    <img src={BASE_URL + "/assets/team3.png"} alt="team 3"></img>
                </div>
            </div>
            <div className="row">
                <div className="col" />
                <div className="col">
                    <img src={BASE_URL + "/assets/team4.png"} alt="team 4"></img>
                </div>
                <div className="col">
                    <img src={BASE_URL + "/assets/team5.png"} alt="team 5"></img>
                </div>
                <div className="col" />
            </div>
        </div>

        <div className="container flex-column align-items-center ">
            <div style={{textAlign: "center", marginTop: "400px"}}>
                <p>
                    Visit @munchrestaurants on Instagram to see what the community is saying
                </p>
            </div>
        </div>
    </div>
  );
}

export default App;
